### ISSUE TITLE
Debian 12.5.0 build "illegal instruction"

### ISSUE THREAD

**Issue by shiny-st** [scash-project/cpuminer-scash#14]
I tried to build the miner from the source and also downloaded the compiled version of it but both gave me the same result.

In the compiled version any kind of command gives me back "illegal instruction", while with the compiling from source version I get the error at the end of the build-linux-static.sh script

**Comment by bitcartel** [comment]
What CPU are you building/running on?

**Comment by shiny-st** [comment]
@bitcartel my bad was an horrible configuration on my part on the VM I'm running it on. Was using the emulated x86-64-v2-AES in Proxmox and didn't think to doublecheck the CPU settings.

Switched to host (ryzen 5 1500x) and it works as intended
